OOP school library: decorate a class
khanh-devos/library-ruby pull request #3
Opened 2023-09-05 14:48 UTC by khanh-devos

- [x] Interface
Create a class Nameable.
Implement a method called correct_name that will raise a NotImplementedError.
Turn your Person class to Nameable
Make sure that your Person class inherits from Nameable
Make sure that this class has a method correct_name implemented. It should simply return the name attribute.
- [x] Prepare base Decorator
Make sure that it inherits from Nameable.
In the constructor assign a nameable object from params to an instance variable.
Implement the correct_name method that returns the result of the correct_name method of the @nameable.
- [x] Prepare CapitalizeDecorator and TrimmerDecorator
For the CapitalizeDecorator:
Create a class that inherits from the base Decorator class.
Implement a method correct_name that capitalizes the output of @nameable.correct_name.
For the TrimmerDecorator:
Create a class that inherits from the base Decorator class.
Implement a method correct_name that makes sure that the output of @nameable.correct_name has a maximum of 10 characters. If it's longer it should trim the word.

- [x] See your decorators in action
Try the following code and check if you managed to decorate your person:

person = Person.new(22, 'maximilianus')
person.correct_name
capitalized_person = CapitalizeDecorator.new(person)
puts capitalized_person.correct_name
capitalized_trimmed_person = TrimmerDecorator.new(capitalized_person)
puts capitalized_trimmed_person.correct_name

2023-09-05 15:52 UTC, FrederickMih requested changes
## Hi :raising_hand: :raising_hand: @khanh-devos , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



<img src="https://media.giphy.com/media/r5eafWP6dcbxX8cLeN/giphy.gif"  width ="150"><img>

## Highlights :green_circle: 

- Nice job for creating all the requested classes :+1: 


## Required Changes ♻️
**N/A**
_Check the comments under the review._

## Optional suggestions
**N/A**
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-05 15:52 UTC, FrederickMih commented on nameable.rb
> +module Nameable
- [ ] Since we are modelling relationship between objects instead of sharing behavior, we are requested to use a class instead of a module. In the requirements of the project, we were told to create a class Nameable and not a module. Let's kindly fix this and adhere to the requirements :smiley:

2023-09-05 15:52 UTC, FrederickMih commented on person.rb
> +  include Nameable
- [ ] As already pointed above :point_up: we should make use of inheritance which is a principle of OOP. I think modules doesn't have instances. Entities and things are most often modeled in classes.

2023-09-05 15:52 UTC, FrederickMih commented on basedecorator.rb
> +  include Nameable
- [ ] Kindly refer to the comment above :arrow_up:

2023-09-05 15:52 UTC, FrederickMih commented on decorators.rb
> +  include BaseDecorator
- [ ] Once more, we shall kindly make use of inheritance.

`class CapitalizeDecorator < BaseDecorator`

2023-09-05 15:52 UTC, FrederickMih commented on decorators.rb
> +  include BaseDecorator
- [ ] kindly refer to comments above :arrow_up:

2023-09-05 16:55 UTC, OyePriscilla approved these changes
Hi @khanh-devos 👏 👏, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![200](https://user-images.githubusercontent.com/103386183/196424328-985f6e98-f7c6-4cf9-bafe-158436f70560.gif)

## Highlights
I`mplemented composition` as an example of the design pattern using `Ruby` ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-05 16:55 UTC, OyePriscilla commented on nameable.rb
> +# p n.correct_name
- [Optional] Kindly remove all the commented lines of code rom your codebase, this will make your codebase to be cleaner and readable. ℹ️

2023-09-05 16:55 UTC, OyePriscilla commented on person.rb
> +    super()
- [optional] Kindly ensure that no linter is disabled, linters are the to catch bugs ahead to improve our project. ℹ️

2023-09-06 06:56 UTC, khanh-devos commented
Thank you very much @OyePriscilla

2023-09-06 06:58 UTC, merged